# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-17 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yy', '0002_auto_20180917_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnormal',
            name='rid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
