# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-19 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yy', '0004_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
