# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-21 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yy', '0005_goods_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='sid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
