# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-21 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yy', '0006_goods_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='sid',
        ),
        migrations.AddField(
            model_name='room',
            name='sid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
